import Layout from '@/components/Layout'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
    <Layout >
        <Head>
          <title>MMDC</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/MMDC.svg" />
        </Head>
        <Component {...pageProps} />
    </Layout>
    
    )
  
}
